Controllers/CuentaController.cs
using NicolasMVC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace NicolasMVC.Controllers
{
    public class CuentaController : Controller
    {
        // GET: Cuenta
       
        public ActionResult Login()
        {
            Cuenta cuenta = new Cuenta();


            return View(cuenta);

        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Clear();
            Session.Abandon();

            return Redirect("~/Home/Index");
        }

        [HttpPost]
        public ActionResult LoginForm(Cuenta model)
        {


            if (ModelState.IsValid)
            {


                string sRet = "";
                DataTable dt = new DataTable();

                sRet = Cuenta.LoginUsuario(model.Usuario.ToString().Trim(), model.Clave.ToString().Trim(), ref dt);

                if (sRet != "")
                {
                    ViewBag.AlertMessage = "Error en el login - " + sRet;
                    ViewBag.Message = "Error en el login - " + sRet;
                    return View("Login", model);
                }


                if (dt.Rows.Count == 1)
                {
                    var authenticationTicket = new FormsAuthenticationTicket(
                1, // Versión de la cookie de autenticación
                model.Usuario, // Nombre del usuario (puedes dejarlo en blanco si lo configurarás después)
                DateTime.Now, // Fecha y hora de inicio de la cookie de autenticación
                DateTime.Now.AddMinutes(30), // Fecha y hora de expiración de la cookie de autenticación
                false // Si la cookie persiste en el disco después de cerrar el navegador (false en este ejemplo)
                , "roles, custom data" // Datos adicionales del usuario (roles, información personalizada, etc.)
            );

                    // Encriptar la cookie de autenticación
                    string encryptedTicket = FormsAuthentication.Encrypt(authenticationTicket);

                    // Crear una cookie de autenticación y agregarla a la respuesta
                    var authenticationCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authenticationCookie);

                    Session["ID"] = dt.Rows[0]["id"];
                    Session["NOMBRE"] = dt.Rows[0]["nombre"];
                    Session["PERFIL"] = dt.Rows[0]["perfil"];
                    Session["PERFIL_ID"] = dt.Rows[0]["perfil_id"];

                    //PASO SIGUIENTE INSTANCIAR EL OBJETO USUARIO/CUENTA, LLENARLO Y ESE OBJETO GUARDARLO EN SESSION


                    return Redirect("~/Home/Index");
                }
                else
                {
                    ViewBag.AlertMessage = "Error en el login";
                    ViewBag.Message = "Error en el login";
                    return View("Login", model);
                }




            }
            else
            {
                return View("Login", model);
            }





        }
    }
}

Views/Shared/MenuSitio.cshtml
<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Formulario", "Formulario", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Noticias", "Index", "Noticias", new { area = "" }, new { @class = "nav-link" })</li>

        @if (Session["PERFIL_ID"] != null && Request.IsAuthenticated == true)
        {

            <ul class="navbar-nav justify-content-end">
                @if (Session["PERFIL_ID"] != null && Request.IsAuthenticated == true)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Administración
                        </a>
                        <ul class="dropdown-menu">

                            <!--MOSTRAR OPCIONES POR PERFILES-->

                            @if (int.Parse(Session["PERFIL_ID"].ToString()) == 1)
                            {
                                <li>@Html.ActionLink("Usuarios", "Index", "Usuarios", new { area = "" }, new { @class = "dropdown-item" })</li>


                                <!--LINK A LA PARTE PRIVADA DEL ADMIN DE NOTICIAS-->
                                <li>@Html.ActionLink("Noticias", "AdminNoticias", "Noticias", new { area = "" }, new { @class = "dropdown-item" })</li>

                            }
                            else
                            {

                                <!--LINK A LA PARTE PRIVADA DEL ADMIN DE NOTICIAS-->
                                <li>@Html.ActionLink("Noticias", "AdminNoticias", "Noticias", new { area = "" }, new { @class = "dropdown-item" })</li>

                            }



                        </ul>
                    </li>
                }

                <li>@Html.ActionLink("Salir", "Logout", "Cuenta", new { area = "" }, new { @class = "nav-link" })</li>

            </ul>

        }
        else
        {
            <ul class="navbar-nav justify-content-end">
                <li>@Html.ActionLink("Ingreso", "Login", "Cuenta", new { area = "" }, new { @class = "nav-link" })</li>

            </ul>


        }



    </ul>
            </li>
        }

    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("MVC NICOLAS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
           <!--MENU-->
            @Html.Partial("MenuSitio")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>


            <p>
                @if (Session["PERFIL_ID"] != null && Request.IsAuthenticated == true)
                {
                    <h4>Sesion activa.</h4>
                  
                    <h5>Usuario: @Session["NOMBRE"] / @Session["PERFIL"]</h5>

                }
                else
                {
                    <h4>Sesion inactiva.</h4>
                  
                    <h5> Usuario sin autenticar.</h5>

                }
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>